[POM-50] feat: 가게 생성 시 공공기관 api를 통한 사업자 등록번호 검증 기능 구현
prgrms-be-devcourse/BE-04-PoMin-Owner pull request #28
Opened 2023-09-13 10:22 UTC by juno-junho

## 📌 설명
- [공공기관 api](https://www.data.go.kr/tcs/dss/selectApiDataDetailView.do?publicDataPk=15081808) 를 통한 사업자등록번호 검증
- 가게 등록 시 검증 기능 구현
- 각 메서드 테스트

2023-09-13 11:09 UTC, Juhongseok commented on src/main/java/com/ray/pominowner/store/controller/StoreController.java
>      }
등록 시에 고객 쪽으로도 전달 해주셔야 해요

2023-09-13 11:11 UTC, Juhongseok commented on src/main/java/com/ray/pominowner/store/service/StoreServiceValidator.java
> +                .get(0);
retun 전 개행 포맷 맞추면 좋겠네요

2023-09-13 11:12 UTC, hyeon-z approved these changes
👍

2023-09-13 11:12 UTC, hyeon-z commented on src/test/java/com/ray/pominowner/store/service/StoreServiceTest.java
> +    private StoreCategoryService storeCategoryService; // mock 안하면 어캐됨?
주석 지워주세요:)

2023-09-13 11:12 UTC, Juhongseok requested changes
고객쪽으로 전달하는 것만 추가 해주세요

2023-09-14 02:25 UTC, beomukim approved these changes
🍣

2023-09-14 02:25 UTC, beomukim commented on src/main/java/com/ray/pominowner/store/service/StoreServiceValidator.java
> +    public void validateBusinessNumber(String businessNumber) throws JsonProcessingException {
이 예외는 전부 던지기만 하는데 처리하는게 좋지 않을까요?

2023-09-14 03:55 UTC, juno-junho commented on src/main/java/com/ray/pominowner/store/service/StoreServiceValidator.java
> +    public void validateBusinessNumber(String businessNumber) throws JsonProcessingException {
나중 exception handler에서 처리해 줄 생각입니다!

2023-09-14 04:08 UTC, ddongpuri approved these changes
😎 고생하셨습니다~

2023-09-14 04:21 UTC, choi5798 approved these changes
🍣

2023-09-14 04:21 UTC, choi5798 commented on src/main/java/com/ray/pominowner/store/service/StoreServiceValidator.java
> +                .get(0);
get(0)은 어떤 것을 가져오는 건가요?

2023-09-14 04:22 UTC, Juhongseok approved these changes
👍

2023-09-14 04:33 UTC, juno-junho commented on src/main/java/com/ray/pominowner/store/service/StoreServiceValidator.java
> +                .get(0);
첫번째 요소를 가져 오는거에요 (list에서)

2023-09-14 04:34 UTC, merged